<a href="https://colab.research.google.com/github/Renan-Domingues/LearnTheBasics-Pytorch/blob/main/Tutorials_01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensors and nympy are very similar... Tensors are optimized for aitomatic differentiation

In [ ]:
import torch
import numpy as np

In [ ]:
# Tendors directly from data

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)


# From NumPy array

np_array = np.array(data)
x_np = torch.from_numpy(np_array)


# from another tensor

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6350, 0.6597],
        [0.4301, 0.7195]]) 



In [ ]:
# with random or constant values

shape = (2,3,) # shape determines the dimensionality of the output tensor. (2 rows, 3 colums)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f" Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.4991, 0.8405, 0.7136],
        [0.9629, 0.4764, 0.3634]]) 

 Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Atributes of a Tensor
Tensors attributes describe their shape, datatype, and the device on which they are stored

In [ ]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on tensors
More tensors operations: https://pytorch.org/docs/stable/torch.html



In [ ]:
# Moving our tensor to the GPU if abailable

if torch.cuda.is_available():
  tensor = tensor.to("cuda")

# Standard numpy-like indexing and slicing:
tensor = torch.ones(4,4)
print(f"first row: {tensor[0]}")
print(f"first column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)


first row: tensor([1., 1., 1., 1.])
first column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


###Joining tensors with torch.cat to concatenate a sequence of tensors along given dimension

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # one dimension (if I tryed with 0 dimension, it wold pile the tensors)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Arithmetic operations

In [ ]:
# this compute the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# this computes the element-wise product. z1, z2, z3 will have the same value

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Single-element tensors -> If you have one-element tensor, for example aggregating all values of a tenso into one value, you can convert it to a Python numerical value using ``item()``:

In [ ]:
agg = tensor.sum()
agg_item = agg.item()

print(type(agg))
print(agg_item, type(agg_item))


<class 'torch.Tensor'>
12.0 <class 'float'>


In-place operations -> Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. for example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.[texto do link](https://)

In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [ ]:
'''
Tensors on the CPU and NumPy arrays can share they indelying memory locations
Changing one will change another
'''
# Tensor to NumPy array

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
# changing 1, will change another

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
# NumPy array to Tensor

n = np.ones(5)
t = torch.from_numpy(n)

# changes in the NumPy array reflects in the tensor.

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
